config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'new/index'
  get 'new/show'
  devise_for :users
  
  get '/homes/about' => 'homes#about',as:'about'
  get 'lists/new'
  post 'lists' => 'lists#create'
  get 'lists' => 'lists#index'
  get 'lists/:id' => 'lists#show', as:'list'
  get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'
  patch 'lists/:id' => 'lists#update', as: 'update_list'
  delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
  resources :users, only: [:show, :edit]
  resources :post_images, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
  
    
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    lists_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
    @lists = List.all
  end
  
  def create
    @list = List.new(list_params)
    @list.user_id=current_user.id
    if @list.save
      flash[:nitice] = "投稿完了しました。"
    redirect_to list_path(@list.id)
    else
      @lists = List.all
      render :index
    end
  end

  def index
    
    @lists = List.all.page(params[:page])
    @list  =List.new
  end

  def show
    @list = List.find(params[:id]) 
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      flash[:notice] = "編集完了しました。"
    redirect_to list_path(@list.id)  
    else
      @lists = List.all
      render :edit
    end
  end
  
  def destroy
    list = List.find(params[:id])  
    list.destroy  
    redirect_to '/lists'  
    flash[:notice] = "削除完了しました。"
  end
  
  private 
  def list_params
    params.require(:list).permit(:title,:body)
  end
  
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
     @post_images = PostImage.page(params[:page])
  end

  def show
  end
  
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @lists = @user.lists.page(params[:page])
    
  
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>ユーザーページ</h1>

app/views/homes/top.html.erb
<h1>ようこそ ゲームレビューサイトゲーれび！ゅへ！</h1>
<p>げーれびゅ！では、さまざまなゲームに関するあなたの意見や</P>
<P>印象を共有し交換することができます</p>

<%= link_to "start", lists_path %>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">ログイン</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">新規登録</a>
          </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/b853f923e4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
      <li>
    <%= link_to '投稿フォーム', lists_path %>
      </li>
      <li>
      <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    </header>
   <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit '保存' %>
  
<% end %>

<%= link_to "show", list_path %>
<a href="/lists">Back</a>

app/views/lists/index.html.erb
<div>
    <%= flash[:notice] %>
    
</div>


<h1>投稿一覧</h1>

<% @lists.each do |list| %>

  <p>タイトル</p>
  <span>
   <%= link_to list.title, list_path(list.id) %>,<%= list.user.name %>,<%= list.created_at.strftime('%Y/%m/%d') %>
  </span>
  
<% end %>
<%= paginate @lists %>


<h1>新規投稿</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list, url: '/lists', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <p><%= f.submit '投稿' %></p>
  
<% end %>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<!-- form_with部分 -->
<%= form_with model: @list do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<div>
     <%= flash[:notice] %>
</div>
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>
<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", destroy_list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<a href="/lists">戻る</a>
 <p>投稿日：<%= @list.created_at.strftime('%Y/%m/%d') %></p>

app/views/new/index.html.erb
<h1>New#index</h1>
<p>Find me in app/views/new/index.html.erb</p>

app/views/new/show.html.erb
<h1>New#show</h1>
<p>Find me in app/views/new/show.html.erb</p>

app/views/post_images/index.html.erb
<% @post_images.each do |post_image| %>
  <div>
    <p>タイトル：<%= post_image.shop_name %></p>
    <p>本文：<%= post_image.caption %></p>
    <p>ユーザーネーム：<%= post_image.user.name %></p>
  </div>
<% end %>

app/views/post_images/new.html.erb
<h1>PostImages#new</h1>
<p>Find me in app/views/post_images/new.html.erb</p>

app/views/post_images/show.html.erb
<h1>PostImages#show</h1>
<p>Find me in app/views/post_images/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>マイページ</h1>
<div>
  <h3>name: <%= @user.name %></h3>
  <h3>email: <%= @user.email %></h3>
  <%= link_to "編集",edit_user_registration_path %>
</div>

<% @lists.each do |list| %>

  <p>タイトル</p>
  <span>
   <%= link_to list.title, list_path(list.id) %>,<%= list.user.name %>
  </span>
  
<% end %>
<%= paginate @lists %>